version: '3.8'

services:
  backend:
    build:
      context: .  # The directory containing the Dockerfile
      dockerfile: Dockerfile.backend  # The name of the Dockerfile
    container_name: nodejs_app
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./nginx/localhost.key:/etc/nginx/certs/localhost.key
    depends_on:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
